### ISSUE TITLE
Update bower file

### ISSUE THREAD

**Issue by cgat** [lemming/angular-flip#3]
Seems like your dependencies are out of date. When I try to install via bower I get the following error:

`bower angular#1.2.0rc1    ENORESTARGET Tag/branch 1.2.0rc1 does not exist`

**Comment by sebtrif** [comment]
Yeap, confirmed, I just tried to install via bower and I have the same issue

**Comment by sebtrif** [comment]
actually, no, nevermind, i have something different:

`bower angular-mocks#1.2.0rc1     ENORESTARGET Tag/branch 1.2.0rc1 does not exist`

it should be `v1.2.0-rc.1`
